import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  tr: {
    // Navigation / Tabs
    "overview": "Kurumsal Dashboard",
    "branches": "Şube Yönetimi",
    "staff": "Çalışan Raporları",
    "menu": "Menü Yönetimi",
    "inventory": "Envanter ve Stok",
    "reports": "Analitik Raporlar",
    "announcements": "Duyuru Panosu",
    "settings": "Sistem Ayarları",
    "branchDashboard": "Şube Dashboard",
    "orders": "Sipariş Kayıtları",
    "reservations": "Rezervasyon Defteri",
    "tables": "Masa Yönetimi",
    "kitchenQueue": "Mutfak Hazırlık Sırası",
    "liveOrders": "Canlı Sipariş Takibi",
    "tableStatus": "Masa Durum Ekranı",
    
    // Login Page
    "login_title": "BranchIQ",
    "login_subtitle": "Kurumsal Restoran Zinciri Yönetim Konsolu",
    "login_btn": "Sistem Konsoluna Giriş Yap",
    "email_placeholder": "Kurumsal E-posta Adresi",
    "password_placeholder": "Giriş Şifresi",
    "demo_accounts": "Hızlı Erişim Demoları (Giriş için tıklayın)",
    "login_error_title": "Giriş Başarısız",
    
    // Sidebar
    "exit_system": "Sistem Konsolundan Çıkış",
    "enterprise_console": "Kurumsal Konsol",
    "developed_by": "Sinem, Merve, Hale, Aslınur tarafından geliştirildi.",
    
    // Navbar
    "scope": "Kapsam:",
    "all_regions": "Tüm Bölgeler",
    "marmara": "Marmara Ağı",
    "central_anatolia": "İç Anadolu Ağı",
    "aegean": "Ege Ağı",
    "secure_core": "Güvenli Çekirdek",
    
    // Dashboard / Common Metrics
    "total_branches": "Toplam Aktif Şube",
    "total_staff": "Toplam Kurumsal Personel",
    "daily_revenue": "Günlük Zincir Cirosu",
    "active_orders": "Aktif Sipariş Miktarı",
    "waiting_reservations": "Bekleyen Rezervasyonlar",
    "critical_stock": "Kritik Limit Altı Stok",
    "branch_performance": "Şube Performans Analizi",
    "revenue_trend": "Aylık Ciro Eğilimi",
    "revenue": "Ciro",
    
    // Branch Detail
    "back_to_branches": "Şube Listesine Geri Dön",
    "branch_details": "Şube Detay Analizi",
    "manager": "Yönetici",
    "status": "Durum",
    "address": "Adres",
    "phone": "Telefon",
    "recent_orders": "Son Sipariş İstasyon Biletleri",
    
    // Employees
    "staff_roster": "Kurumsal Çalışan Kadrosu",
    "add_employee": "Yeni Personel Tanımla",
    "edit_employee": "Personel Bilgilerini Güncelle",
    "employee_name": "Ad Soyad",
    "role": "Görev",
    "shift": "Vardiya",
    "performance": "Performans",
    "salary": "Maaş",
    
    // Menu
    "menu_catalog": "Kurumsal Menü Kataloğu",
    "add_dish": "Yeni Menü Ürünü Ekle",
    "dish_name": "Ürün Adı",
    "category": "Kategori",
    "price": "Fiyat",
    "cost": "Maliyet",
    
    // Inventory
    "inventory_ledger": "Stok ve Depo Envanteri",
    "add_stock": "Yeni Stok Kalemi Ekle",
    "stock_name": "Malzeme Adı",
    "quantity": "Miktar",
    "unit": "Birim",
    "min_limit": "Kritik Miktar Limiti",
    "supplier": "Tedarikçi Firma",
    
    // Reports
    "gross_revenue": "Brüt Bölgesel Gelir",
    "completed_orders": "Tamamlanan Siparişler",
    "avg_order_value": "Ortalama Sipariş Tutarı",
    
    // Reservations
    "reservations_book": "Masa Rezervasyon Defteri",
    "add_booking": "Yeni Rezervasyon Planla",
    "customer_name": "Müşteri Ad Soyad",
    "guests": "Kişi Sayısı",
    "date": "Tarih",
    "time": "Saat",
    "assigned_table": "Atanan Masa",
    
    // Kitchen Queue
    "kitchen_console": "Mutfak Operasyon Konsolu",
    "kitchen_active": "Mutfak Motoru Aktif",
    "incoming_tickets": "Gelen Biletler (Yeni)",
    "in_prep": "Hazırlanıyor",
    "ready_pickup": "Servise Hazır",
    
    // Tables
    "seating_layout": "İnteraktif Oturma Düzeni",
    "total_seats": "Toplam Oturma Kapasitesi",
    "available_tables": "Boş / Müsait Masalar",
    "occupied_tables": "Dolu Masalar",
    "cleaning_tables": "Temizlenen Masalar",
    
    // SuperAdminDashboard
    "latest_broadcast_notice": "Son Duyuru Yayını",
    "view_board": "Panoyu Görüntüle",
    "monthly_gross_revenue": "Aylık Brüt Ciro",
    "aggregate_orders": "Toplam Sipariş",
    "average_ticket_value": "Ortalama Sipariş Tutarı",
    "active_staff_members": "Aktif Personel Sayısı",
    "weekly_system_revenue": "Haftalık Sistem Ciro Analizi",
    "consolidated_billing": "Seçilen bölgelerdeki konsolide edilmiş fatura tutarları",
    "live_feed": "Canlı Akış",
    "regional_performance_share": "Bölgesel Performans Payı",
    "percentage_contribution": "Toplam aylık ciroya yüzde katkısı",
    "system_total": "Sistem Toplamı",
    "no_regional_data": "Bölgesel veri bulunamadı",
    "active_kitchen_orders": "Aktif Mutfak Sipariş Kuyruğu",
    "pending_kitchen_tickets": "mutfak siparişi hazırlanmayı bekliyor",
    "manage_queues": "Kuyrukları Yönet",
    "no_pending_orders": "Mutfakta bekleyen sipariş bulunmuyor.",
    "branch_operations_status": "Şube Operasyon Durumları",
    "functional_state_nodes": "Fiziksel şube düğümlerinin işlevsel durumu",
    "online": "Çevrimiçi",
    "offline": "Çevrimdışı",
    "revenue_vs_last_month": "geçen aya göre",
    "orders_vs_last_week": "geçen haftaya göre",
    "pricing_optimization": "fiyatlandırma optimizasyonu",
    "across_branches": "şube genelinde",

    // Branches
    "search_branches_placeholder": "Şubeleri isim, konum veya yöneticiye göre ara...",
    "all_statuses": "Tüm Durumlar",
    "active": "Aktif",
    "inactive": "Aktif Değil",
    "add_branch_node": "Yeni Şube Ekle",
    "monthly_gross": "Aylık Ciro",
    "daily_orders": "Günlük Sipariş",
    "regional_hq": "Bölge Ağı:",
    "general_manager": "Genel Yönetici:",
    "table_count_label": "Masa Sayısı:",
    "quality_rating": "Kalite Puanı:",
    "contact": "İletişim:",
    "view_analytics": "Analitiği Görüntüle",
    "configure": "Yapılandır",
    "decommission": "Şubeyi Devre Dışı Bırak",
    "no_branches_located": "Kayıtlı Şube Bulunamadı",
    "reset_filter_params": "Filtre parametrelerini veya arama sorgusunu sıfırlamayı deneyin.",
    "update_branch_details": "Şube Detaylarını Güncelle",
    "provision_new_branch": "Yeni Şube Ekle",
    "branch_name": "Şube Adı*",
    "city": "Şehir*",
    "region_network": "Bölge Ağı*",
    "general_manager_name": "Genel Yönetici Adı*",
    "address_label": "Adres*",
    "monthly_gross_revenue_label": "Aylık Brüt Ciro ($)",
    "avg_daily_orders_label": "Ortalama Günlük Sipariş",
    "phone_number_label": "Telefon Numarası*",
    "table_count": "Masa Sayısı",
    "cancel": "İptal",
    "provision_node": "Şubeyi Ekle",
    "delete_branch_confirm": "Bu şubeyi kurumsal ağdan kalıcı olarak silmek istediğinize emin misiniz?",

    // BranchDetail
    "select_branch_analytics": "Detaylı analitiği görüntülemek için lütfen bir şube seçin.",
    "go_back": "Geri Dön",
    "analytics_title": "Analizi",
    "city_node": "Şubesi",
    "region_label": "Bölgesi",
    "monthly_revenue": "Aylık Ciro",
    "total_orders_simulated": "Toplam Sipariş (Simüle)",
    "staff_count": "Personel Sayısı",
    "tables_configured": "Kayıtlı Masalar",
    "node_demographics": "Şube Bilgileri",
    "address_location": "Adres Bilgisi",
    "store_manager": "Şube Müdürü",
    "branch_telephone": "Şube Telefonu",
    "no_phone_set": "Telefon tanımlanmamış",
    "performance_rating": "Performans Puanı",
    "stars": "Yıldız",
    "assigned_staff_directory": "Görevli Personel Listesi",
    "no_employees_assigned": "Bu şubeye atanmış çalışan bulunmamaktadır.",
    "last_7_days": "Son 7 Gün",
    "last_30_days": "Son 30 Gün",
    "low_performance": "Düşük Performans",
    "export_report": "Verileri Dışa Aktar",
    "export_success": "Rapor başarıyla üretildi ve indirildi!",
    "simulation_active": "Canlı Sipariş Simülatörü: Aktif",
    "simulation_paused": "Canlı Sipariş Simülatörü: Kapalı",
    "live_redux_console": "Canlı Redux Event Log Konsolu",
    "clear_console": "Konsolu Temizle",
    "no_events_logged": "Redux olay kuyruğu boş. Sipariş Simülatörünü aktif ederek izleyebilirsiniz.",
    "enterprise_analytics_reports": "Kurumsal Analiz & Raporlar",
    "monitor_financial_indices": "Gerçek zamanlı finansal endeksleri, satış dağılımlarını ve bölgesel hedefleri izleyin.",
    "this_week": "Bu Hafta",
    "this_month": "Bu Ay",
    "fiscal_year": "Mali Yıl",
    "export_ledger": "Raporu Dışa Aktar",
    "gross_regional_income": "Brüt Bölgesel Gelir",
    "fulfilled_orders_ledger": "Tamamlanan Sipariş Kayıtları",
    "average_ticket_valuation": "Ortalama Bilet Değeri",
    "average_store_rating": "Ortalama Şube Puanı",
    "vs_last_period": "önceki döneme göre",
    "consolidated_ticket_price": "Konsolide sepet ortalaması",
    "customer_satisfaction_index": "Müşteri memnuniyeti endeksi",
    "consolidated_revenue_comparison": "Konsolide Gelir Karşılaştırması",
    "order_fulfilment_channel": "Sipariş Kanalı Dağılımı",
    "no_channel_records": "Kayıtlı sipariş kanalı bulunamadı.",
    
    // Kitchen / Operation
    "live_kitchen_queue": "Canlı Mutfak Sipariş Kuyruğu",
    "track_cooking_tickets": "Mutfak sipariş biletlerini, hazırlık sürelerini ve ürün kontrol listelerini takip edin.",
    "kitchen_engine_active": "Mutfak Motoru Aktif",
    "incoming_tickets_new": "Yeni Gelen Siparişler",
    "active_in_prep": "Hazırlanan Siparişler",
    "ready_for_pickup": "Teslime Hazır Siparişler",
    "new_tickets": "Yeni Biletler",
    "preparing": "Hazırlanıyor",
    "ready_for_service": "Servise Hazır",
    "mark_preparing": "Hazırlamaya Başla",
    "mark_ready": "Hazır Olarak İşaretle",
    "complete_order": "Siparişi Tamamla",
    "dish_prep_checklist": "Sipariş Hazırlık Listesi",
    "special_requests": "Özel İstekler:",
    "no_special_requests": "Özel bir istek belirtilmedi.",
    "no_new_tickets": "Yeni sipariş bileti yok",
    "no_orders_preparing": "Hazırlanan sipariş yok",
    "no_orders_ready": "Teslime hazır sipariş yok",
    
    // Live Order Monitor
    "ops_dashboard": "Operasyon Kontrol Paneli",
    "live_order_monitor": "Canlı Sipariş Takip Paneli",
    "monitor_active_orders": "Aktif siparişlerin hazırlık durumlarını, mutfak yoğunluğunu ve dağıtım planlamalarını izleyin.",
    "avg_prep_time": "Ort. Hazırlık Süresi",
    "kitchen_load": "Mutfak Yoğunluğu",
    "fire_prep": "Hazırlığı Başlat",
    "ready_up": "Hazırla",
    "complete": "Tamamla",
    
    // Table Status
    "floor_ops": "Saha & Salon Operasyonları",
    "live_table_console": "Canlı Masa Durumu Konsolu",
    "monitor_seating_capacity": "Masaların doluluk oranlarını, temizlik durumlarını, rezervasyonları ve aktif sipariş tutarlarını izleyin.",
    "total_seating_slots": "Toplam Masa Kapasitesi",
    "tables_in_cleaning": "Temizlenen Masalar",
    "capacity": "Kapasite",
    "change_status": "Durumu Değiştir",
    "section": "Bölüm",
    "main_hall": "Ana Salon",
    
    // Branch Dashboard
    "local_branch_panel": "Lokal Şube Paneli",
    "welcome": "Hoş Geldiniz",
    "operational_command_for_node": "Şube operasyonel yönetim paneli:",
    "target_region_scope": "Bölge Ağı Kapsamı",
    "sector": "Bölgesi",
    "local_revenue": "Lokal Ciro",
    "calculated_from_ledger": "Sipariş defterinden hesaplandı",
    "total_orders": "Toplam Sipariş",
    "includes_off_premise_tickets": "Paket/gel-al siparişler dahil",
    "active_preparing": "Aktif Hazırlanan",
    "pending_kitchen_pickup": "Mutfakta hazırlanmayı bekliyor",
    "total_tables": "Toplam Masa",
    "interactive_layout": "İnteraktif masa yerleşimi",
    "recent_station_tickets": "Son Sipariş İstasyon Biletleri",
    "no_active_station_tickets": "Bugün kayıtlı aktif sipariş bileti bulunmuyor.",
    "contact_information": "İletişim Bilgileri",
    "node_address": "Şube Adresi",
    "telephone_line": "Telefon Hattı",
    "operational_status": "Operasyonel Durum",
    
    // Orders Panel
    "all_orders": "Tüm Siparişler",
    "pending_kitchen": "Bekleyen Sipariş",
    "preparing_food": "Hazırlanan Yemekler",
    "dispatched_done": "Tamamlanan / Teslim",
    "cancelled": "İptal Edilenler",
    "search_orders_placeholder": "Sipariş Kodu, müşteri veya şube adına göre ara...",
    "all_branches": "Tüm Şubeler",
    "place_new_guest_order": "Yeni Sipariş Oluştur",
    "order_code": "Sipariş Kodu",
    "location_branch": "Şube Konumu",
    "customer": "Müşteri",
    "kitchen_status": "Mutfak Durumu",
    "order_type": "Tür",
    "total_amount": "Toplam Tutar",
    "actions": "İşlemler",
    "inspect_order_items": "Sipariş İçeriğini İncele",
    "start_cooking": "Hazırlığı Başlat",
    "dispatch": "Teslim Et",
    "no_orders_in_queue": "Kuyrukta Sipariş Bulunmuyor",
    "operational_queues_clear": "Operasyonel mutfak kuyrukları tamamen temiz.",
    "order_details_title": "Sipariş Detayları:",
    "ordered_culinary_items": "Sipariş Edilen Yemekler",
    "grand_total": "Genel Toplam",
    "advance_to_cooking": "Hazırlanıyor Aşamasına Geçir",
    "advance_to_dispatched": "Tamamlandı / Teslim Edildi Yap",
    "cancel_this_order": "Siparişi İptal Et",
    "purge_transaction_record": "Sipariş Kaydını Sistemden Sil",
    "place_guest_mock_order": "Yeni Simüle Sipariş Ekle",
    "target_branch": "Hedef Şube*",
    "service_type": "Servis Türü*",
    "dish_quantity_selector": "Yemek & Adet Seçimi",
    "add_item": "Yemek Ekle",
    "dispatch_to_kitchen": "Mutfak Sırasına Gönder",
    
    // Reservations Panel
    "manage_customer_seating": "Müşteri oturma düzenlerini, VIP listelerini ve konuk sayılarını yönetin.",
    "schedule_booking": "Rezervasyon Planla",
    "confirmed_bookings": "Onaylanan Rezervasyonlar",
    "total_guest_covers": "Toplam Konuk Sayısı",
    "avg_seating_size": "Ortalama Masa Büyüklüğü",
    "search_booking_placeholder": "Rezervasyon listesini müşteri adına göre ara...",
    "date_time": "Tarih & Saat",
    "no_reservations": "Kayıtlı Rezervasyon Bulunmuyor",
    "no_reservations_subtitle": "Aktif aramayı kontrol edin veya ilk rezervasyon kaydını oluşturun.",
    "edit_guest_booking": "Rezervasyonu Düzenle",
    "customer_full_name": "Müşteri Adı Soyadı*",
    "guests_count": "Kişi Sayısı*",
    "seating_assignment": "Masa Ataması*",
    "select_a_table": "Masa Seçin",
    "date_target": "Rezervasyon Tarihi*",
    "arrival_time_target": "Varış Saati*",
    "contact_phone_line": "İrtibat Telefonu",
    "booking_status": "Rezervasyon Durumu",
    "confirm_booking": "Rezervasyonu Onayla",
    
    // Table Management Panel
    "track_occupancy_limits": "Gerçek zamanlı doluluk oranlarını, masa bölgesi yoğunluklarını ve konuk oturma limitlerini takip edin.",
    "add_table_slot": "Masa Slotu Ekle",
    "consolidated_seating_cap": "Konsolide Masa Kapasitesi",
    "seats": "Kişilik",
    "mark_occupied": "Dolu Olarak İşaretle",
    "occupied": "Dolu",
    "deploy_first_table": "Yukarıdaki düğmeden ilk interaktif masa yerleşimini tanımlayın.",
    "edit_table_config": "Masa Konfigürasyonunu Düzenle",
    "introduce_seating_slot": "Yeni Masa Ekle",
    "seating_label": "Masa Etiketi/Kodu*",
    "max_capacity": "Maksimum Kapasite (Kişi)*",
    "section_area": "Salon Bölgesi",
    "initial_occupancy": "Başlangıç Doluluk Durumu",
    "deploy_table_slot": "Masayı Ekle",
    
    // Employees Panel
    "search_staff_placeholder": "Çalışan adı, unvan veya e-posta ile ara...",
    "onboard_employee": "Yeni Personel Onboard Et",
    "assigned_node": "Atanan Şube",
    "roster_status": "Kadro Durumu",
    "direct_email": "E-posta Adresi",
    "contact_phone": "İrtibat Telefonu",
    "dismiss": "İşten Çıkar",
    "no_staff_listed": "Kayıtlı Çalışan Bulunmuyor",
    "staff_subtitle": "Filtreleri daraltın veya yeni bir çalışan ekleyin.",
    "update_staff_member": "Çalışan Bilgilerini Güncelle",
    "full_legal_name": "Tam Adı Soyadı*",
    "roster_email": "E-posta Adresi*",
    "store_node_assignment": "Şube Ataması*",
    "operational_role": "Operasyonel Unvan*",
    "contact_phone_required": "İrtibat Telefonu*",
    "roster_status_required": "Kadro Durumu*",
    "commit_onboard": "Onboard Et",
    "save_updates": "Güncellemeleri Kaydet",
    
    // Campaigns / Announcements Panel
    "corporate_notices": "Kurumsal Duyuru Yayınları",
    "notices_subtitle": "Yönergeleri, politika düzenlemelerini ve şube başarılarını iletin.",
    "broadcast_notice": "Duyuru Yayınla",
    "sender": "Gönderen",
    "announcements_empty": "Duyuru Panosu Boş",
    "employees_up_to_date": "Tüm çalışanlar en güncel bilgilere sahip.",
    "notice_type_group": "Duyuru Tipi Grubu*",
    "notice_headline": "Duyuru Başlığı*",
    "notice_content_text": "Duyuru İçerik Metni*",
    "info_standard": "Bilgilendirme (Standart Bilgi)",
    "success_achievement": "Başarı (Tebrik / Kutlama)",
    "warning_urgent": "Uyarı (Acil Durum / Bakım)",
    
    // Inventory Management Panel
    "track_key_ingredients": "Ana malzemeleri, mutfak ekipmanlarını ve kritik limit tetikleyicilerini takip edin.",
    "total_tracked_items": "Toplam Takip Edilen Ürün",
    "critical_shortage_triggers": "Kritik Stok Uyarısı",
    "supply_depots_connected": "Bağlı Depolar",
    "hq_regional_nodes": "Merkez & Bölge Depoları",
    "search_stock_placeholder": "Stok kataloğunda ara...",
    "show_low_stock_only": "Sadece Kritik Stokları Göster",
    "no_stock_items": "Kayıtlı Stok Kalemi Bulunmuyor",
    "no_stock_subtitle": "Arama parametrelerini kontrol edin veya ilk stok kaydını oluşturun.",
    "edit_supply_listing": "Stok Kalemini Düzenle",
    "stock_name_required": "Malzeme Adı*",
    "quantity_required": "Stok Miktarı*",
    "measurement_unit": "Ölçü Birimi*",
    "min_limit_required": "Kritik Miktar Limiti*",
    "node_location": "Depo Konumu",
    "save_stock_item": "Stok Kalemini Kaydet",
    
    // Menu Management Panel
    "search_menu_placeholder": "Menü ürünleri, içecekler veya açıklamalarda ara...",
    "all_categories": "Tüm Kategoriler",
    "in_stock": "Stokta Var",
    "out_of_stock": "Stokta Yok",
    "no_menu_items": "Kayıtlı Menü Ürünü Bulunmuyor",
    "no_menu_subtitle": "Arama terimlerini değiştirin veya standart kategoriler tanımlayın.",
    "edit_culinary_listing": "Menü Ürününü Düzenle",
    "culinary_name_required": "Ürün Adı*",
    "category_required": "Kategori*",
    "price_required": "Birim Fiyat ($)*",
    "description_required": "Ürün Açıklaması*",
    "activate_availability": "Bu ürünü hemen stokta aktif olarak işaretle",
    "publish_dish": "Ürünü Yayınla",
    
    // Settings Panel
    "settings_title": "Sistem Ayarları & Parametreler",
    "settings_subtitle": "Kullanıcı profilinizi, aktif oturum kapsamlarını, genel tetikleyicileri ve otomatik veri yedekleme parametrelerini yönetin.",
    "profile_config": "Profil Yapılandırması",
    "full_operational_name": "Tam Operasyonel İsim",
    "security_access_email": "Güvenlik Erişim E-postası",
    "regional_preferences": "Bölgesel Tercihler",
    "system_locale_language": "Sistem Dili",
    "operational_region_limit": "Operasyonel Bölge Sınırı",
    "interactive_system_flags": "Etkileşimli Sistem Bayrakları",
    "parameters_saved_success": "✓ Parametreler başarıyla kaydedildi",
    "save_settings": "Ayarları Kaydet"
  },
  en: {
    // Navigation / Tabs
    "overview": "Super Dashboard",
    "branches": "Branch Operations",
    "staff": "Employees Roster",
    "menu": "Menu Catalog",
    "inventory": "Inventory Stock",
    "reports": "Financial Reports",
    "announcements": "Notice Broadcasts",
    "settings": "System Settings",
    "branchDashboard": "Local Dashboard",
    "orders": "Orders Registry",
    "reservations": "Table Reservations",
    "tables": "Table Management",
    "kitchenQueue": "Kitchen Queue",
    "liveOrders": "Live Orders",
    "tableStatus": "Table Status",
    
    // Login Page
    "login_title": "BranchIQ",
    "login_subtitle": "Enterprise Restaurant Chain Management",
    "login_btn": "Sign In to System Console",
    "email_placeholder": "Email Address",
    "password_placeholder": "Password",
    "demo_accounts": "Quick Demo Accounts (Click to login)",
    "login_error_title": "Authentication Failed",
    
    // Sidebar
    "exit_system": "Exit System Console",
    "enterprise_console": "Enterprise Console",
    "developed_by": "Developed by Sinem, Merve, Hale, Aslınur.",
    
    // Navbar
    "scope": "Scope:",
    "all_regions": "All Regions",
    "marmara": "Marmara Network",
    "central_anatolia": "Central Anatolia Network",
    "aegean": "Aegean Network",
    "secure_core": "Secure Core",
    
    // Dashboard / Common Metrics
    "total_branches": "Total Active Branches",
    "total_staff": "Total Staff Directory",
    "daily_revenue": "Daily Chain Income",
    "active_orders": "Active Station Tickets",
    "waiting_reservations": "Waiting Reservations",
    "critical_stock": "Critical Stock Items",
    "branch_performance": "Branch Performance Index",
    "revenue_trend": "Monthly Revenue Trend",
    "revenue": "Revenue",
    
    // Branch Detail
    "back_to_branches": "Back to Branch List",
    "branch_details": "Branch Detail Analysis",
    "manager": "Manager",
    "status": "Status",
    "address": "Address",
    "phone": "Phone",
    "recent_orders": "Recent Station Tickets",
    
    // Employees
    "staff_roster": "Employees Roster",
    "add_employee": "Add Employee",
    "edit_employee": "Edit Employee Details",
    "employee_name": "Full Name",
    "role": "Role",
    "shift": "Shift",
    "performance": "Performance",
    "salary": "Salary",
    
    // Menu
    "menu_catalog": "Corporate Menu Catalog",
    "add_dish": "Add Product",
    "dish_name": "Product Name",
    "category": "Category",
    "price": "Price",
    "cost": "Cost",
    
    // Inventory
    "inventory_ledger": "Inventory Stock Ledger",
    "add_stock": "Add Stock Item",
    "stock_name": "Ingredient Name",
    "quantity": "Quantity",
    "unit": "Unit",
    "min_limit": "Min Limit",
    "supplier": "Supplier",
    
    // Reports
    "gross_revenue": "Gross Regional Income",
    "completed_orders": "Completed Orders",
    "avg_order_value": "Avg. Order Value",
    
    // Reservations
    "reservations_book": "Table Reservations Book",
    "add_booking": "Schedule Guest Booking",
    "customer_name": "Customer Name",
    "guests": "Guest Size",
    "date": "Date",
    "time": "Time",
    "assigned_table": "Assigned Table",
    
    // Kitchen Queue
    "kitchen_console": "Back-Of-House Console",
    "kitchen_active": "Kitchen Engine Active",
    "incoming_tickets": "Incoming Tickets (New)",
    "in_prep": "Active In-Prep",
    "ready_pickup": "Ready for Pick-Up",
    
    // Tables
    "seating_layout": "Interactive Seating Layout",
    "total_seats": "Total Seating Slots",
    "available_tables": "Available Tables",
    "occupied_tables": "Occupied Tables",
    "cleaning_tables": "Tables in Cleaning",

    // SuperAdminDashboard
    "latest_broadcast_notice": "Latest Broadcast Notice",
    "view_board": "View Board",
    "monthly_gross_revenue": "Monthly Gross Revenue",
    "aggregate_orders": "Aggregate Orders",
    "average_ticket_value": "Average Ticket Value",
    "active_staff_members": "Active Staff Members",
    "weekly_system_revenue": "Weekly System Revenue Analytics",
    "consolidated_billing": "Consolidated billing figures across designated regions",
    "live_feed": "Live Feed",
    "regional_performance_share": "Regional Performance Share",
    "percentage_contribution": "Percentage contribution to total monthly gross",
    "system_total": "System Total",
    "no_regional_data": "No regional data available",
    "active_kitchen_orders": "Active Kitchen Orders Queue",
    "pending_kitchen_tickets": "pending kitchen tickets require preparation",
    "manage_queues": "Manage Queues",
    "no_pending_orders": "No pending orders in the kitchen.",
    "branch_operations_status": "Branch Operations Status",
    "functional_state_nodes": "Functional state of the physical store nodes",
    "online": "Online",
    "offline": "Offline",
    "revenue_vs_last_month": "vs last month",
    "orders_vs_last_week": "vs last week",
    "pricing_optimization": "pricing optimization",
    "across_branches": "across branches",

    // Branches
    "search_branches_placeholder": "Search branches by name, location, or manager...",
    "all_statuses": "All Statuses",
    "active": "Active",
    "inactive": "Inactive",
    "add_branch_node": "Add Branch Node",
    "monthly_gross": "Monthly Gross",
    "daily_orders": "Daily Orders",
    "regional_hq": "Regional HQ:",
    "general_manager": "General Manager:",
    "table_count_label": "Table Count:",
    "quality_rating": "Quality Rating:",
    "contact": "Contact:",
    "view_analytics": "View Analytics",
    "configure": "Configure",
    "decommission": "Decommission",
    "no_branches_located": "No Branch Nodes Located",
    "reset_filter_params": "Try resetting your filter parameters or search queries.",
    "update_branch_details": "Update Branch Details",
    "provision_new_branch": "Provision New Branch",
    "branch_name": "Branch Name*",
    "city": "City*",
    "region_network": "Region Network*",
    "general_manager_name": "General Manager Name*",
    "address_label": "Address*",
    "monthly_gross_revenue_label": "Monthly Gross Revenue ($)",
    "avg_daily_orders_label": "Average Daily Orders",
    "phone_number_label": "Phone Number*",
    "table_count": "Table Count",
    "cancel": "Cancel",
    "provision_node": "Provision Node",
    "delete_branch_confirm": "Are you sure you want to permanently delete this branch node from the enterprise?",

    // BranchDetail
    "select_branch_analytics": "Please select a branch to view detailed analytics.",
    "go_back": "Go Back",
    "analytics_title": "Analytics",
    "city_node": "Node",
    "region_label": "Region",
    "monthly_revenue": "Monthly Revenue",
    "total_orders_simulated": "Total Orders (Simulated)",
    "staff_count": "Staff Count",
    "tables_configured": "Tables Configured",
    "node_demographics": "Node Demographics",
    "address_location": "Address Location",
    "store_manager": "Store Manager",
    "branch_telephone": "Branch Telephone",
    "no_phone_set": "No phone set",
    "performance_rating": "Performance Rating",
    "stars": "Stars",
    "assigned_staff_directory": "Assigned Staff Directory",
    "no_employees_assigned": "No employees explicitly assigned to this store node.",
    "last_7_days": "Last 7 Days",
    "last_30_days": "Last 30 Days",
    "low_performance": "Underperforming",
    "export_report": "Export Report",
    "export_success": "Report compiled and downloaded successfully!",
    "simulation_active": "Live Order Simulator: Active",
    "simulation_paused": "Live Order Simulator: Paused",
    "live_redux_console": "Live Redux Event Log Console",
    "clear_console": "Clear Console",
    "no_events_logged": "Redux event queue is empty. Activate the Order Simulator to observe logs.",
    "enterprise_analytics_reports": "Enterprise Analytics & Reports",
    "monitor_financial_indices": "Monitor real-time financial indices, sales distribution, and regional targets.",
    "this_week": "This Week",
    "this_month": "This Month",
    "fiscal_year": "Fiscal Year",
    "export_ledger": "Export Ledger",
    "gross_regional_income": "Gross Regional Income",
    "fulfilled_orders_ledger": "Fulfilled Orders Ledger",
    "average_ticket_valuation": "Average Ticket Valuation",
    "average_store_rating": "Average Store Rating",
    "vs_last_period": "vs Last Period",
    "consolidated_ticket_price": "Consolidated ticket price",
    "customer_satisfaction_index": "Customer satisfaction index",
    "consolidated_revenue_comparison": "Consolidated Revenue Comparison",
    "order_fulfilment_channel": "Order Fulfilment Channel Distribution",
    "no_channel_records": "No order channel records registered yet.",
    
    // Kitchen / Operation
    "live_kitchen_queue": "Live Kitchen Preparation Queue",
    "track_cooking_tickets": "Track real-time cooking tickets, elapsed SLAs, and dish checklists.",
    "kitchen_engine_active": "Kitchen Engine Active",
    "incoming_tickets_new": "Incoming Tickets (New)",
    "active_in_prep": "Active In-Prep (Preparing)",
    "ready_for_pickup": "Ready for Pick-Up",
    "new_tickets": "New Tickets",
    "preparing": "Preparing",
    "ready_for_service": "Ready for Service",
    "mark_preparing": "Mark Preparing",
    "mark_ready": "Mark Ready",
    "complete_order": "Complete Order",
    "dish_prep_checklist": "Dish Prep Checklist",
    "special_requests": "Special Requests:",
    "no_special_requests": "No special requests.",
    "no_new_tickets": "No new tickets",
    "no_orders_preparing": "No orders in preparation",
    "no_orders_ready": "No orders ready for pickup",
    
    // Live Order Monitor
    "ops_dashboard": "Operations Dashboard",
    "live_order_monitor": "Real-Time Live Order Monitor",
    "monitor_active_orders": "Monitor active orders, preparation statuses, kitchen throughput and dispatcher schedules.",
    "avg_prep_time": "Avg. Prep Time",
    "kitchen_load": "Kitchen Load",
    "fire_prep": "Fire Prep",
    "ready_up": "Ready Up",
    "complete": "Complete",
    
    // Table Status
    "floor_ops": "Floor Operations",
    "live_table_console": "Live Table Status Console",
    "monitor_seating_capacity": "Monitor seating capacity, clean statuses, reservations, and active order totals.",
    "total_seating_slots": "Total Seating Slots",
    "tables_in_cleaning": "Tables in Cleaning",
    "capacity": "Capacity",
    "change_status": "Change Status",
    "section": "Section",
    "main_hall": "Main Hall",
    
    // Branch Dashboard
    "local_branch_panel": "Local Branch Panel",
    "welcome": "Welcome",
    "operational_command_for_node": "Operational command for node:",
    "target_region_scope": "Target Region Scope",
    "sector": "Sector",
    "local_revenue": "Local Revenue",
    "calculated_from_ledger": "Calculated from ledger",
    "total_orders": "Total Orders",
    "includes_off_premise_tickets": "Includes off-premise tickets",
    "active_preparing": "Active Preparing",
    "pending_kitchen_pickup": "Pending kitchen pickup",
    "total_tables": "Total Tables",
    "interactive_layout": "Interactive layout",
    "recent_station_tickets": "Recent Station Tickets",
    "no_active_station_tickets": "No active station tickets registered today.",
    "contact_information": "Contact Information",
    "node_address": "Node Address",
    "telephone_line": "Telephone Line",
    "operational_status": "Operational Status",
    
    // Orders Panel
    "all_orders": "All Orders",
    "pending_kitchen": "Pending Kitchen",
    "preparing_food": "Preparing Food",
    "dispatched_done": "Dispatched / Done",
    "cancelled": "Cancelled",
    "search_orders_placeholder": "Search by Order ID, customer, branch name...",
    "all_branches": "All Branches",
    "place_new_guest_order": "Place New Guest Order",
    "order_code": "Order Code",
    "location_branch": "Location Branch",
    "customer": "Customer",
    "kitchen_status": "Kitchen Status",
    "order_type": "Type",
    "total_amount": "Total Amount",
    "actions": "Actions",
    "inspect_order_items": "Inspect Order Items",
    "start_cooking": "Start cooking",
    "dispatch": "Dispatch",
    "no_orders_in_queue": "No Orders in Queue",
    "operational_queues_clear": "Operational queues are completely clear.",
    "order_details_title": "Order Details:",
    "ordered_culinary_items": "Ordered Culinary Items",
    "grand_total": "Grand Total",
    "advance_to_cooking": "Advance to Cooking Kitchen",
    "advance_to_dispatched": "Advance to Dispatched/Completed",
    "cancel_this_order": "Cancel This Order",
    "purge_transaction_record": "Purge Transaction Record",
    "place_guest_mock_order": "Place Guest Mock Order",
    "target_branch": "Target Branch*",
    "service_type": "Service Type*",
    "dish_quantity_selector": "Dish & Quantity Selector",
    "dispatch_to_kitchen": "Dispatch to Kitchen",
    
    // Reservations Panel
    "manage_customer_seating": "Manage customer seating timetables, vip lists, and guest counts.",
    "schedule_booking": "Schedule Booking",
    "confirmed_bookings": "Confirmed Bookings",
    "total_guest_covers": "Total Guest Covers",
    "avg_seating_size": "Average Seating Size",
    "search_booking_placeholder": "Search booking list by name...",
    "date_time": "Date & Time",
    "no_reservations": "No Reservations Listed",
    "no_reservations_subtitle": "Double check active query or create the first booking cover.",
    "edit_guest_booking": "Edit Guest Booking",
    "customer_full_name": "Customer Full Name*",
    "guests_count": "Guests Cover Count*",
    "seating_assignment": "Seating Assignment*",
    "select_a_table": "Select a Table",
    "date_target": "Date Target*",
    "arrival_time_target": "Arrival Time Target*",
    "contact_phone_line": "Contact Phone Line",
    "booking_status": "Booking Status",
    "confirm_booking": "Confirm Booking",
    
    // Table Management Panel
    "track_occupancy_limits": "Track real-time occupancy, table section densities, and guest seating limits.",
    "add_table_slot": "Add Table Slot",
    "consolidated_seating_cap": "Consolidated Seating Cap",
    "seats": "Seats",
    "mark_occupied": "Mark Occupied",
    "occupied": "Occupied",
    "deploy_first_table": "Deploy the first interactive table coordinates above.",
    "edit_table_config": "Edit Table Configuration",
    "introduce_seating_slot": "Introduce Seating Slot",
    "seating_label": "Seating Label/Code*",
    "max_capacity": "Maximum Capacity (Pax)*",
    "section_area": "Section Area",
    "initial_occupancy": "Initial Occupancy",
    "deploy_table_slot": "Deploy Table Slot",
    
    // Employees Panel
    "search_staff_placeholder": "Search by staff name, role, email...",
    "onboard_employee": "Onboard Employee",
    "assigned_node": "Assigned Node",
    "roster_status": "Roster Status",
    "direct_email": "Direct Email",
    "contact_phone": "Contact Phone",
    "dismiss": "Dismiss",
    "no_staff_listed": "No Staff Members Listed",
    "staff_subtitle": "Refine filters, scope boundaries, or onboard new employees.",
    "update_staff_member": "Update Staff Member",
    "full_legal_name": "Full Legal Name*",
    "roster_email": "Roster Email*",
    "store_node_assignment": "Store Node Assignment*",
    "operational_role": "Operational Role*",
    "contact_phone_required": "Contact Phone*",
    "roster_status_required": "Roster Status*",
    "commit_onboard": "Commit Onboard",
    "save_updates": "Save Updates",
    
    // Campaigns / Announcements Panel
    "corporate_notices": "Corporate Notice Broadcasts",
    "notices_subtitle": "Communicate guidelines, policy adjustments, and branch achievements.",
    "broadcast_notice": "Broadcast Notice",
    "sender": "Sender",
    "announcements_empty": "Announcement Board Empty",
    "employees_up_to_date": "All employees are completely up to date.",
    "notice_type_group": "Notice Type Group*",
    "notice_headline": "Notice Headline*",
    "notice_content_text": "Notice Content Text*",
    "info_standard": "Information (Standard Info)",
    "success_achievement": "Success (Achievement Celebration)",
    "warning_urgent": "Warning (Urgent Maintenance / Attention)",
    
    // Inventory Management Panel
    "track_key_ingredients": "Track key ingredients, kitchen utensils, and threshold triggers.",
    "total_tracked_items": "Total Tracked Items",
    "critical_shortage_triggers": "Critical Shortage Triggers",
    "supply_depots_connected": "Supply Depots Connected",
    "hq_regional_nodes": "HQ & Regional Nodes",
    "search_stock_placeholder": "Search stock catalog...",
    "show_low_stock_only": "Show Low Stock Only",
    "no_stock_items": "No Stock Items Found",
    "no_stock_subtitle": "Double check search parameters or introduce first stock listing.",
    "edit_supply_listing": "Edit Supply Listing",
    "stock_name_required": "Stock Item Name*",
    "quantity_required": "Available Quantity*",
    "measurement_unit": "Measurement Unit*",
    "min_limit_required": "Low Limit Threshold*",
    "node_location": "Node Location",
    "save_stock_item": "Save Stock Item",
    
    // Menu Management Panel
    "search_menu_placeholder": "Search dishes, drinks, descriptors...",
    "all_categories": "All Categories",
    "in_stock": "In Stock",
    "out_of_stock": "Out of Stock",
    "no_menu_items": "No Menu Items Found",
    "no_menu_subtitle": "Adjust search terms or create standard categories.",
    "edit_culinary_listing": "Edit Culinary Listing",
    "culinary_name_required": "Culinary Name*",
    "category_required": "Category*",
    "price_required": "Unit Price ($)*",
    "description_required": "Culinary Description*",
    "activate_availability": "Activate immediate in-stock listing availability",
    "publish_dish": "Publish Dish",
    
    // Settings Panel
    "settings_title": "System Settings & Parameters",
    "settings_subtitle": "Manage your user profile, active session scopes, global triggers, and automatic data backup parameters.",
    "profile_config": "Profile Configuration",
    "full_operational_name": "Full Operational Name",
    "security_access_email": "Security Access Email",
    "regional_preferences": "Regional Preferences",
    "system_locale_language": "System Locale Language",
    "operational_region_limit": "Operational Region Limit",
    "interactive_system_flags": "Interactive System Flags",
    "parameters_saved_success": "✓ Parameters saved successfully",
    "save_settings": "Save Settings"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('branchiq_lang') || 'tr';
  });

  useEffect(() => {
    localStorage.setItem('branchiq_lang', language);
  }, [language]);

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
